### ISSUE TITLE
Mispelling

### ISSUE THREAD

**Issue by plac** [MarcelLZ/barbecue-company#4]
Correct me if I'm wrong, but shouldn't it be `PORT` ?

https://github.com/MarcelLZ/barbecue-company/blob/6d56465d1f436a2af320a183678e9aefd6ec1cf7/backend/src/index.js#L15

**Comment by MarcelLZ** [comment]
Hahahaha. Thanks, @plac! You're right, I'll change it when I go to work on the backend.

**Comment by MarcelLZ** [comment]
Thanks, @plac! It was corrected!
